// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: course_enrollments.sql

package dbgen

import (
	"context"
)

const enrollStudent = `-- name: EnrollStudent :exec
INSERT OR IGNORE INTO course_enrollments (user_id, course_id) VALUES (?, ?)
`

type EnrollStudentParams struct {
	UserID   string
	CourseID string
}

func (q *Queries) EnrollStudent(ctx context.Context, arg EnrollStudentParams) error {
	_, err := q.db.ExecContext(ctx, enrollStudent, arg.UserID, arg.CourseID)
	return err
}

const getEnrolledCourseIDs = `-- name: GetEnrolledCourseIDs :many
SELECT course_id FROM course_enrollments WHERE user_id = ?
`

func (q *Queries) GetEnrolledCourseIDs(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getEnrolledCourseIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var course_id string
		if err := rows.Scan(&course_id); err != nil {
			return nil, err
		}
		items = append(items, course_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnrolledStudents = `-- name: GetEnrolledStudents :many
SELECT users.id, users.name, users.email,
    COALESCE((
        SELECT SUM(quiz_grades.grade)
        FROM quiz_grades
        JOIN quizzes ON quizzes.id = quiz_grades.quiz_id
        WHERE quiz_grades.user_id = users.id AND quizzes.course_id = course_enrollments.course_id
    ), 0) AS points
FROM course_enrollments
JOIN users ON users.id = course_enrollments.user_id
WHERE course_enrollments.course_id = ?
ORDER BY users.name
`

type GetEnrolledStudentsRow struct {
	ID     string
	Name   string
	Email  string
	Points interface{}
}

func (q *Queries) GetEnrolledStudents(ctx context.Context, courseID string) ([]GetEnrolledStudentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getEnrolledStudents, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEnrolledStudentsRow
	for rows.Next() {
		var i GetEnrolledStudentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Points,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnenrolledStudents = `-- name: GetUnenrolledStudents :many
SELECT users.id, users.name, users.email
FROM users
WHERE users.role = 'student'
  AND users.id NOT IN (SELECT user_id FROM course_enrollments WHERE course_id = ?)
ORDER BY users.name
`

type GetUnenrolledStudentsRow struct {
	ID    string
	Name  string
	Email string
}

func (q *Queries) GetUnenrolledStudents(ctx context.Context, courseID string) ([]GetUnenrolledStudentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUnenrolledStudents, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnenrolledStudentsRow
	for rows.Next() {
		var i GetUnenrolledStudentsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isEnrolled = `-- name: IsEnrolled :one
SELECT EXISTS(SELECT 1 FROM course_enrollments WHERE user_id = ? AND course_id = ?)
`

type IsEnrolledParams struct {
	UserID   string
	CourseID string
}

func (q *Queries) IsEnrolled(ctx context.Context, arg IsEnrolledParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isEnrolled, arg.UserID, arg.CourseID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const unenrollStudent = `-- name: UnenrollStudent :exec
DELETE FROM course_enrollments WHERE user_id = ? AND course_id = ?
`

type UnenrollStudentParams struct {
	UserID   string
	CourseID string
}

func (q *Queries) UnenrollStudent(ctx context.Context, arg UnenrollStudentParams) error {
	_, err := q.db.ExecContext(ctx, unenrollStudent, arg.UserID, arg.CourseID)
	return err
}
