// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: courses.sql

package dbgen

import (
	"context"
)

const addCourse = `-- name: AddCourse :exec
INSERT INTO courses (id, title, description, category, hlc, origin_node)
VALUES (?, ?, ?, ?, ?, ?)
`

type AddCourseParams struct {
	ID          string
	Title       string
	Description string
	Category    string
	Hlc         int64
	OriginNode  string
}

func (q *Queries) AddCourse(ctx context.Context, arg AddCourseParams) error {
	_, err := q.db.ExecContext(ctx, addCourse,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Hlc,
		arg.OriginNode,
	)
	return err
}

const getCourse = `-- name: GetCourse :one
SELECT id, title, description, category, hlc, origin_node FROM courses WHERE id = ?
`

func (q *Queries) GetCourse(ctx context.Context, id string) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Hlc,
		&i.OriginNode,
	)
	return i, err
}

const getCourses = `-- name: GetCourses :many
SELECT id, title, description, category, hlc, origin_node FROM courses ORDER BY rowid
`

func (q *Queries) GetCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, getCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Hlc,
			&i.OriginNode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
