// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: forum_links.sql

package dbgen

import (
	"context"
	"database/sql"
)

const addForumLink = `-- name: AddForumLink :exec
INSERT INTO forum_links (source_post_id, target_id, target_type) VALUES (?, ?, ?)
`

type AddForumLinkParams struct {
	SourcePostID string
	TargetID     string
	TargetType   string
}

func (q *Queries) AddForumLink(ctx context.Context, arg AddForumLinkParams) error {
	_, err := q.db.ExecContext(ctx, addForumLink, arg.SourcePostID, arg.TargetID, arg.TargetType)
	return err
}

const getCourseForumLinkedLessons = `-- name: GetCourseForumLinkedLessons :many
SELECT lessons.id, lessons.course_id, lessons.title, courses.title AS course_title
FROM lessons
JOIN courses ON courses.id = lessons.course_id
WHERE lessons.id IN (
    SELECT forum_links.target_id
    FROM forum_links
    JOIN forum_posts ON forum_posts.id = forum_links.source_post_id
    WHERE forum_posts.course_id = ? AND forum_links.target_type = 'lesson'
)
ORDER BY lessons.rowid
`

type GetCourseForumLinkedLessonsRow struct {
	ID          string
	CourseID    string
	Title       string
	CourseTitle string
}

func (q *Queries) GetCourseForumLinkedLessons(ctx context.Context, courseID string) ([]GetCourseForumLinkedLessonsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCourseForumLinkedLessons, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCourseForumLinkedLessonsRow
	for rows.Next() {
		var i GetCourseForumLinkedLessonsRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.CourseTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourseForumLinkedLibraryItems = `-- name: GetCourseForumLinkedLibraryItems :many
SELECT library_items.id, library_items.title, library_items.type, library_items.category, library_items.size_kb, library_items.mime_type, library_items.original_filename, library_items.uploaded_at, library_items.modified_at, library_items.duration, library_items.resolution, library_items.file_path, library_items.uploaded_by, users.name AS uploaded_by_name
FROM library_items
LEFT JOIN users ON library_items.uploaded_by = users.id
WHERE library_items.id IN (
    SELECT forum_links.target_id
    FROM forum_links
    JOIN forum_posts ON forum_posts.id = forum_links.source_post_id
    WHERE forum_posts.course_id = ? AND forum_links.target_type = 'library_item'
)
ORDER BY library_items.rowid
`

type GetCourseForumLinkedLibraryItemsRow struct {
	ID               string
	Title            string
	Type             string
	Category         string
	SizeKb           int64
	MimeType         string
	OriginalFilename string
	UploadedAt       string
	ModifiedAt       string
	Duration         sql.NullString
	Resolution       sql.NullString
	FilePath         string
	UploadedBy       sql.NullString
	UploadedByName   sql.NullString
}

func (q *Queries) GetCourseForumLinkedLibraryItems(ctx context.Context, courseID string) ([]GetCourseForumLinkedLibraryItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCourseForumLinkedLibraryItems, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCourseForumLinkedLibraryItemsRow
	for rows.Next() {
		var i GetCourseForumLinkedLibraryItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.Category,
			&i.SizeKb,
			&i.MimeType,
			&i.OriginalFilename,
			&i.UploadedAt,
			&i.ModifiedAt,
			&i.Duration,
			&i.Resolution,
			&i.FilePath,
			&i.UploadedBy,
			&i.UploadedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourseForumLinkedQuizzes = `-- name: GetCourseForumLinkedQuizzes :many
SELECT quizzes.id, quizzes.course_id, quizzes.title, courses.title AS course_title
FROM quizzes
JOIN courses ON courses.id = quizzes.course_id
WHERE quizzes.id IN (
    SELECT forum_links.target_id
    FROM forum_links
    JOIN forum_posts ON forum_posts.id = forum_links.source_post_id
    WHERE forum_posts.course_id = ? AND forum_links.target_type = 'quiz'
)
ORDER BY quizzes.rowid
`

type GetCourseForumLinkedQuizzesRow struct {
	ID          string
	CourseID    string
	Title       string
	CourseTitle string
}

func (q *Queries) GetCourseForumLinkedQuizzes(ctx context.Context, courseID string) ([]GetCourseForumLinkedQuizzesRow, error) {
	rows, err := q.db.QueryContext(ctx, getCourseForumLinkedQuizzes, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCourseForumLinkedQuizzesRow
	for rows.Next() {
		var i GetCourseForumLinkedQuizzesRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.CourseTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
