// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: forum.sql

package dbgen

import (
	"context"
	"database/sql"
)

const addForumPost = `-- name: AddForumPost :exec
INSERT INTO forum_posts (id, course_id, parent_id, user_id, title, body, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type AddForumPostParams struct {
	ID        string
	CourseID  string
	ParentID  sql.NullString
	UserID    string
	Title     string
	Body      string
	CreatedAt string
}

func (q *Queries) AddForumPost(ctx context.Context, arg AddForumPostParams) error {
	_, err := q.db.ExecContext(ctx, addForumPost,
		arg.ID,
		arg.CourseID,
		arg.ParentID,
		arg.UserID,
		arg.Title,
		arg.Body,
		arg.CreatedAt,
	)
	return err
}

const getForumPost = `-- name: GetForumPost :one
SELECT id, course_id, parent_id, user_id, title, body, created_at FROM forum_posts WHERE id = ?
`

func (q *Queries) GetForumPost(ctx context.Context, id string) (ForumPost, error) {
	row := q.db.QueryRowContext(ctx, getForumPost, id)
	var i ForumPost
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.ParentID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const getForumPostsForCourse = `-- name: GetForumPostsForCourse :many
SELECT forum_posts.id, forum_posts.course_id, forum_posts.parent_id, forum_posts.user_id,
    forum_posts.title, forum_posts.body, forum_posts.created_at,
    users.name AS author_name, users.role AS author_role,
    (SELECT COUNT(*) FROM forum_likes WHERE forum_likes.post_id = forum_posts.id) AS like_count
FROM forum_posts
JOIN users ON users.id = forum_posts.user_id
WHERE forum_posts.course_id = ?
ORDER BY forum_posts.created_at
`

type GetForumPostsForCourseRow struct {
	ID         string
	CourseID   string
	ParentID   sql.NullString
	UserID     string
	Title      string
	Body       string
	CreatedAt  string
	AuthorName string
	AuthorRole string
	LikeCount  int64
}

func (q *Queries) GetForumPostsForCourse(ctx context.Context, courseID string) ([]GetForumPostsForCourseRow, error) {
	rows, err := q.db.QueryContext(ctx, getForumPostsForCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetForumPostsForCourseRow
	for rows.Next() {
		var i GetForumPostsForCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.ParentID,
			&i.UserID,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorName,
			&i.AuthorRole,
			&i.LikeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLikedPostIDsForCourse = `-- name: GetLikedPostIDsForCourse :many
SELECT forum_likes.post_id
FROM forum_likes
JOIN forum_posts ON forum_posts.id = forum_likes.post_id
WHERE forum_likes.user_id = ? AND forum_posts.course_id = ?
`

type GetLikedPostIDsForCourseParams struct {
	UserID   string
	CourseID string
}

func (q *Queries) GetLikedPostIDsForCourse(ctx context.Context, arg GetLikedPostIDsForCourseParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getLikedPostIDsForCourse, arg.UserID, arg.CourseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var post_id string
		if err := rows.Scan(&post_id); err != nil {
			return nil, err
		}
		items = append(items, post_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const likePost = `-- name: LikePost :exec
INSERT OR IGNORE INTO forum_likes (post_id, user_id) VALUES (?, ?)
`

type LikePostParams struct {
	PostID string
	UserID string
}

func (q *Queries) LikePost(ctx context.Context, arg LikePostParams) error {
	_, err := q.db.ExecContext(ctx, likePost, arg.PostID, arg.UserID)
	return err
}

const unlikePost = `-- name: UnlikePost :exec
DELETE FROM forum_likes WHERE post_id = ? AND user_id = ?
`

type UnlikePostParams struct {
	PostID string
	UserID string
}

func (q *Queries) UnlikePost(ctx context.Context, arg UnlikePostParams) error {
	_, err := q.db.ExecContext(ctx, unlikePost, arg.PostID, arg.UserID)
	return err
}
