// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lessons.sql

package dbgen

import (
	"context"
	"database/sql"
)

const addLesson = `-- name: AddLesson :exec
INSERT INTO lessons (id, course_id, title, content_text) VALUES (?, ?, ?, ?)
`

type AddLessonParams struct {
	ID          string
	CourseID    string
	Title       string
	ContentText string
}

func (q *Queries) AddLesson(ctx context.Context, arg AddLessonParams) error {
	_, err := q.db.ExecContext(ctx, addLesson,
		arg.ID,
		arg.CourseID,
		arg.Title,
		arg.ContentText,
	)
	return err
}

const getAllLessonsWithCourse = `-- name: GetAllLessonsWithCourse :many
SELECT lessons.id, lessons.course_id, lessons.title, courses.title AS course_title
FROM lessons
JOIN courses ON courses.id = lessons.course_id
ORDER BY lessons.rowid
`

type GetAllLessonsWithCourseRow struct {
	ID          string
	CourseID    string
	Title       string
	CourseTitle string
}

func (q *Queries) GetAllLessonsWithCourse(ctx context.Context) ([]GetAllLessonsWithCourseRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllLessonsWithCourse)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllLessonsWithCourseRow
	for rows.Next() {
		var i GetAllLessonsWithCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.CourseTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLesson = `-- name: GetLesson :one
SELECT lessons.id, lessons.course_id, lessons.title, lessons.content_text, quizzes.id AS quiz_id
FROM lessons
LEFT JOIN quizzes ON quizzes.lesson_id = lessons.id
WHERE lessons.id = ?
`

type GetLessonRow struct {
	ID          string
	CourseID    string
	Title       string
	ContentText string
	QuizID      sql.NullString
}

func (q *Queries) GetLesson(ctx context.Context, id string) (GetLessonRow, error) {
	row := q.db.QueryRowContext(ctx, getLesson, id)
	var i GetLessonRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.ContentText,
		&i.QuizID,
	)
	return i, err
}

const getLessonsForCourse = `-- name: GetLessonsForCourse :many
SELECT lessons.id, lessons.course_id, lessons.title, lessons.content_text, quizzes.id AS quiz_id
FROM lessons
LEFT JOIN quizzes ON quizzes.lesson_id = lessons.id
WHERE lessons.course_id = ?
ORDER BY lessons.rowid
`

type GetLessonsForCourseRow struct {
	ID          string
	CourseID    string
	Title       string
	ContentText string
	QuizID      sql.NullString
}

func (q *Queries) GetLessonsForCourse(ctx context.Context, courseID string) ([]GetLessonsForCourseRow, error) {
	rows, err := q.db.QueryContext(ctx, getLessonsForCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLessonsForCourseRow
	for rows.Next() {
		var i GetLessonsForCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.ContentText,
			&i.QuizID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLesson = `-- name: UpdateLesson :exec
UPDATE lessons SET title = ?, content_text = ? WHERE id = ?
`

type UpdateLessonParams struct {
	Title       string
	ContentText string
	ID          string
}

func (q *Queries) UpdateLesson(ctx context.Context, arg UpdateLessonParams) error {
	_, err := q.db.ExecContext(ctx, updateLesson, arg.Title, arg.ContentText, arg.ID)
	return err
}
