// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lesson_links.sql

package dbgen

import (
	"context"
	"database/sql"
)

const addLessonLink = `-- name: AddLessonLink :exec
INSERT INTO lesson_links (source_lesson_id, target_id, target_type) VALUES (?, ?, ?)
`

type AddLessonLinkParams struct {
	SourceLessonID string
	TargetID       string
	TargetType     string
}

func (q *Queries) AddLessonLink(ctx context.Context, arg AddLessonLinkParams) error {
	_, err := q.db.ExecContext(ctx, addLessonLink, arg.SourceLessonID, arg.TargetID, arg.TargetType)
	return err
}

const deleteLessonLinks = `-- name: DeleteLessonLinks :exec
DELETE FROM lesson_links WHERE source_lesson_id = ?
`

func (q *Queries) DeleteLessonLinks(ctx context.Context, sourceLessonID string) error {
	_, err := q.db.ExecContext(ctx, deleteLessonLinks, sourceLessonID)
	return err
}

const getLessonsLinkingToTarget = `-- name: GetLessonsLinkingToTarget :many
SELECT lessons.id, lessons.course_id, lessons.title, courses.title AS course_title
FROM lesson_links
JOIN lessons ON lessons.id = lesson_links.source_lesson_id
JOIN courses ON courses.id = lessons.course_id
WHERE lesson_links.target_id = ?
ORDER BY lessons.rowid
`

type GetLessonsLinkingToTargetRow struct {
	ID          string
	CourseID    string
	Title       string
	CourseTitle string
}

func (q *Queries) GetLessonsLinkingToTarget(ctx context.Context, targetID string) ([]GetLessonsLinkingToTargetRow, error) {
	rows, err := q.db.QueryContext(ctx, getLessonsLinkingToTarget, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLessonsLinkingToTargetRow
	for rows.Next() {
		var i GetLessonsLinkingToTargetRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.CourseTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkedLessons = `-- name: GetLinkedLessons :many
SELECT lessons.id, lessons.course_id, lessons.title, courses.title AS course_title
FROM lesson_links
JOIN lessons ON lessons.id = lesson_links.target_id
JOIN courses ON courses.id = lessons.course_id
WHERE lesson_links.source_lesson_id = ? AND lesson_links.target_type = 'lesson'
ORDER BY lessons.rowid
`

type GetLinkedLessonsRow struct {
	ID          string
	CourseID    string
	Title       string
	CourseTitle string
}

func (q *Queries) GetLinkedLessons(ctx context.Context, sourceLessonID string) ([]GetLinkedLessonsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLinkedLessons, sourceLessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLinkedLessonsRow
	for rows.Next() {
		var i GetLinkedLessonsRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.CourseTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkedLibraryItems = `-- name: GetLinkedLibraryItems :many
SELECT library_items.id, library_items.title, library_items.type, library_items.category, library_items.size_kb, library_items.mime_type, library_items.original_filename, library_items.uploaded_at, library_items.modified_at, library_items.duration, library_items.resolution, library_items.file_path, library_items.uploaded_by, users.name AS uploaded_by_name
FROM lesson_links
JOIN library_items ON library_items.id = lesson_links.target_id
LEFT JOIN users ON library_items.uploaded_by = users.id
WHERE lesson_links.source_lesson_id = ? AND lesson_links.target_type = 'library_item'
ORDER BY library_items.rowid
`

type GetLinkedLibraryItemsRow struct {
	ID               string
	Title            string
	Type             string
	Category         string
	SizeKb           int64
	MimeType         string
	OriginalFilename string
	UploadedAt       string
	ModifiedAt       string
	Duration         sql.NullString
	Resolution       sql.NullString
	FilePath         string
	UploadedBy       sql.NullString
	UploadedByName   sql.NullString
}

func (q *Queries) GetLinkedLibraryItems(ctx context.Context, sourceLessonID string) ([]GetLinkedLibraryItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLinkedLibraryItems, sourceLessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLinkedLibraryItemsRow
	for rows.Next() {
		var i GetLinkedLibraryItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.Category,
			&i.SizeKb,
			&i.MimeType,
			&i.OriginalFilename,
			&i.UploadedAt,
			&i.ModifiedAt,
			&i.Duration,
			&i.Resolution,
			&i.FilePath,
			&i.UploadedBy,
			&i.UploadedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
