// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lessons.sql

package dbgen

import (
	"context"
	"database/sql"
)

const addLesson = `-- name: AddLesson :exec
INSERT INTO lessons (id, course_id, title, content_text, library_item_id) VALUES (?, ?, ?, ?, ?)
`

type AddLessonParams struct {
	ID            string
	CourseID      string
	Title         string
	ContentText   string
	LibraryItemID sql.NullString
}

func (q *Queries) AddLesson(ctx context.Context, arg AddLessonParams) error {
	_, err := q.db.ExecContext(ctx, addLesson,
		arg.ID,
		arg.CourseID,
		arg.Title,
		arg.ContentText,
		arg.LibraryItemID,
	)
	return err
}

const getLesson = `-- name: GetLesson :one
SELECT lessons.id, lessons.course_id, lessons.title, lessons.content_text, lessons.library_item_id, quizzes.id AS quiz_id
FROM lessons
LEFT JOIN quizzes ON quizzes.lesson_id = lessons.id
WHERE lessons.id = ?
`

type GetLessonRow struct {
	ID            string
	CourseID      string
	Title         string
	ContentText   string
	LibraryItemID sql.NullString
	QuizID        sql.NullString
}

func (q *Queries) GetLesson(ctx context.Context, id string) (GetLessonRow, error) {
	row := q.db.QueryRowContext(ctx, getLesson, id)
	var i GetLessonRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.ContentText,
		&i.LibraryItemID,
		&i.QuizID,
	)
	return i, err
}

const getLessonsForCourse = `-- name: GetLessonsForCourse :many
SELECT lessons.id, lessons.course_id, lessons.title, lessons.content_text, lessons.library_item_id, quizzes.id AS quiz_id
FROM lessons
LEFT JOIN quizzes ON quizzes.lesson_id = lessons.id
WHERE lessons.course_id = ?
ORDER BY lessons.rowid
`

type GetLessonsForCourseRow struct {
	ID            string
	CourseID      string
	Title         string
	ContentText   string
	LibraryItemID sql.NullString
	QuizID        sql.NullString
}

func (q *Queries) GetLessonsForCourse(ctx context.Context, courseID string) ([]GetLessonsForCourseRow, error) {
	rows, err := q.db.QueryContext(ctx, getLessonsForCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLessonsForCourseRow
	for rows.Next() {
		var i GetLessonsForCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.ContentText,
			&i.LibraryItemID,
			&i.QuizID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLesson = `-- name: UpdateLesson :exec
UPDATE lessons SET title = ?, content_text = ?, library_item_id = ? WHERE id = ?
`

type UpdateLessonParams struct {
	Title         string
	ContentText   string
	LibraryItemID sql.NullString
	ID            string
}

func (q *Queries) UpdateLesson(ctx context.Context, arg UpdateLessonParams) error {
	_, err := q.db.ExecContext(ctx, updateLesson,
		arg.Title,
		arg.ContentText,
		arg.LibraryItemID,
		arg.ID,
	)
	return err
}
