// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: library_items.sql

package dbgen

import (
	"context"
	"database/sql"
)

const addLibraryItem = `-- name: AddLibraryItem :exec
INSERT INTO library_items (
    id, title, type, category, size_kb, mime_type, original_filename,
    uploaded_at, modified_at, duration, resolution, file_path, uploaded_by
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type AddLibraryItemParams struct {
	ID               string
	Title            string
	Type             string
	Category         string
	SizeKb           int64
	MimeType         string
	OriginalFilename string
	UploadedAt       string
	ModifiedAt       string
	Duration         sql.NullString
	Resolution       sql.NullString
	FilePath         string
	UploadedBy       sql.NullString
}

func (q *Queries) AddLibraryItem(ctx context.Context, arg AddLibraryItemParams) error {
	_, err := q.db.ExecContext(ctx, addLibraryItem,
		arg.ID,
		arg.Title,
		arg.Type,
		arg.Category,
		arg.SizeKb,
		arg.MimeType,
		arg.OriginalFilename,
		arg.UploadedAt,
		arg.ModifiedAt,
		arg.Duration,
		arg.Resolution,
		arg.FilePath,
		arg.UploadedBy,
	)
	return err
}

const getLibraryItem = `-- name: GetLibraryItem :one
SELECT library_items.id, library_items.title, library_items.type, library_items.category, library_items.size_kb, library_items.mime_type, library_items.original_filename, library_items.uploaded_at, library_items.modified_at, library_items.duration, library_items.resolution, library_items.file_path, library_items.uploaded_by, users.name AS uploaded_by_name FROM library_items
LEFT JOIN users ON library_items.uploaded_by = users.id
WHERE library_items.id = ?
`

type GetLibraryItemRow struct {
	ID               string
	Title            string
	Type             string
	Category         string
	SizeKb           int64
	MimeType         string
	OriginalFilename string
	UploadedAt       string
	ModifiedAt       string
	Duration         sql.NullString
	Resolution       sql.NullString
	FilePath         string
	UploadedBy       sql.NullString
	UploadedByName   sql.NullString
}

func (q *Queries) GetLibraryItem(ctx context.Context, id string) (GetLibraryItemRow, error) {
	row := q.db.QueryRowContext(ctx, getLibraryItem, id)
	var i GetLibraryItemRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.Category,
		&i.SizeKb,
		&i.MimeType,
		&i.OriginalFilename,
		&i.UploadedAt,
		&i.ModifiedAt,
		&i.Duration,
		&i.Resolution,
		&i.FilePath,
		&i.UploadedBy,
		&i.UploadedByName,
	)
	return i, err
}

const getLibraryItems = `-- name: GetLibraryItems :many
SELECT library_items.id, library_items.title, library_items.type, library_items.category, library_items.size_kb, library_items.mime_type, library_items.original_filename, library_items.uploaded_at, library_items.modified_at, library_items.duration, library_items.resolution, library_items.file_path, library_items.uploaded_by, users.name AS uploaded_by_name FROM library_items
LEFT JOIN users ON library_items.uploaded_by = users.id
ORDER BY library_items.rowid
`

type GetLibraryItemsRow struct {
	ID               string
	Title            string
	Type             string
	Category         string
	SizeKb           int64
	MimeType         string
	OriginalFilename string
	UploadedAt       string
	ModifiedAt       string
	Duration         sql.NullString
	Resolution       sql.NullString
	FilePath         string
	UploadedBy       sql.NullString
	UploadedByName   sql.NullString
}

func (q *Queries) GetLibraryItems(ctx context.Context) ([]GetLibraryItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLibraryItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLibraryItemsRow
	for rows.Next() {
		var i GetLibraryItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.Category,
			&i.SizeKb,
			&i.MimeType,
			&i.OriginalFilename,
			&i.UploadedAt,
			&i.ModifiedAt,
			&i.Duration,
			&i.Resolution,
			&i.FilePath,
			&i.UploadedBy,
			&i.UploadedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalDiskKB = `-- name: TotalDiskKB :one
SELECT COALESCE(SUM(size_kb), 0) FROM library_items
`

func (q *Queries) TotalDiskKB(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, totalDiskKB)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const updateLibraryItem = `-- name: UpdateLibraryItem :exec
UPDATE library_items SET
    title = ?, category = ?, size_kb = ?, mime_type = ?, original_filename = ?,
    duration = ?, resolution = ?, file_path = ?
WHERE id = ?
`

type UpdateLibraryItemParams struct {
	Title            string
	Category         string
	SizeKb           int64
	MimeType         string
	OriginalFilename string
	Duration         sql.NullString
	Resolution       sql.NullString
	FilePath         string
	ID               string
}

func (q *Queries) UpdateLibraryItem(ctx context.Context, arg UpdateLibraryItemParams) error {
	_, err := q.db.ExecContext(ctx, updateLibraryItem,
		arg.Title,
		arg.Category,
		arg.SizeKb,
		arg.MimeType,
		arg.OriginalFilename,
		arg.Duration,
		arg.Resolution,
		arg.FilePath,
		arg.ID,
	)
	return err
}
