// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
)

type Course struct {
	ID          string
	Title       string
	Description string
	Category    string
	Hlc         int64
	OriginNode  string
}

type CourseEnrollment struct {
	UserID   string
	CourseID string
}

type ForumLike struct {
	PostID string
	UserID string
}

type ForumLink struct {
	SourcePostID string
	TargetID     string
	TargetType   string
}

type ForumPost struct {
	ID         string
	CourseID   string
	ParentID   sql.NullString
	UserID     string
	Title      string
	Body       string
	CreatedAt  string
	Hlc        int64
	OriginNode string
}

type Lesson struct {
	ID          string
	CourseID    string
	Title       string
	ContentText string
	Hlc         int64
	OriginNode  string
}

type LessonLink struct {
	SourceLessonID string
	TargetID       string
	TargetType     string
}

type LibraryItem struct {
	ID               string
	Title            string
	Type             string
	Category         string
	SizeKb           int64
	MimeType         string
	OriginalFilename string
	UploadedAt       string
	ModifiedAt       string
	Duration         sql.NullString
	Resolution       sql.NullString
	FilePath         string
	UploadedBy       sql.NullString
	Hlc              int64
	OriginNode       string
}

type Quiz struct {
	ID          string
	CourseID    string
	LessonID    sql.NullString
	Title       string
	Description string
	Value       int64
	Hlc         int64
	OriginNode  string
}

type QuizGrade struct {
	UserID     string
	QuizID     string
	Grade      int64
	GradedAt   string
	Hlc        int64
	OriginNode string
}

type QuizLink struct {
	SourceQuizID string
	TargetID     string
	TargetType   string
}

type QuizQuestion struct {
	ID           string
	QuizID       string
	Ordinal      int64
	Text         string
	OptionsJson  string
	CorrectIndex int64
	Hlc          int64
	OriginNode   string
}

type ServerLog struct {
	ID        int64
	Timestamp string
	Level     string
	Message   string
	Fields    string
}

type ServerLogsFt struct {
	Message string
}

type SyncOp struct {
	Seq        int64
	OriginNode string
	TableName  string
	PkJson     string
	Op         string
	Hlc        int64
	Payload    string
	Label      string
	CreatedAt  string
}

type SyncPeer struct {
	Peer       string
	NodeID     string
	LastSeq    int64
	LastSyncAt string
	LastError  string
}

type SyncReader struct {
	NodeID   string
	AckedSeq int64
	LastSeen string
}

type User struct {
	ID           string
	Name         string
	Email        string
	PasswordHash string
	Role         string
	Hlc          int64
	OriginNode   string
}

type UserCompletedLesson struct {
	UserID   string
	LessonID string
}
