// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
)

type Course struct {
	ID          string
	Title       string
	Description string
	Category    string
}

type CourseEnrollment struct {
	UserID   string
	CourseID string
}

type ForumLike struct {
	PostID string
	UserID string
}

type ForumLink struct {
	SourcePostID string
	TargetID     string
	TargetType   string
}

type ForumPost struct {
	ID        string
	CourseID  string
	ParentID  sql.NullString
	UserID    string
	Title     string
	Body      string
	CreatedAt string
}

type Lesson struct {
	ID          string
	CourseID    string
	Title       string
	ContentText string
}

type LessonLink struct {
	SourceLessonID string
	TargetID       string
	TargetType     string
}

type LibraryItem struct {
	ID               string
	Title            string
	Type             string
	Category         string
	SizeKb           int64
	MimeType         string
	OriginalFilename string
	UploadedAt       string
	ModifiedAt       string
	Duration         sql.NullString
	Resolution       sql.NullString
	FilePath         string
	UploadedBy       sql.NullString
}

type Quiz struct {
	ID          string
	CourseID    string
	LessonID    sql.NullString
	Title       string
	Description string
	Value       int64
}

type QuizGrade struct {
	UserID   string
	QuizID   string
	Grade    int64
	GradedAt string
}

type QuizLink struct {
	SourceQuizID string
	TargetID     string
	TargetType   string
}

type QuizQuestion struct {
	ID           string
	QuizID       string
	Ordinal      int64
	Text         string
	OptionsJson  string
	CorrectIndex int64
}

type ServerLog struct {
	ID        int64
	Timestamp string
	Level     string
	Message   string
	Fields    string
}

type ServerLogsFt struct {
	Message string
}

type SyncLog struct {
	ID        int64
	Action    string
	CreatedAt string
}

type User struct {
	ID           string
	Name         string
	Email        string
	PasswordHash string
	Role         string
}

type UserCompletedLesson struct {
	UserID   string
	LessonID string
}
