// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"
)

type Querier interface {
	AddCompletedLesson(ctx context.Context, arg AddCompletedLessonParams) error
	AddCourse(ctx context.Context, arg AddCourseParams) error
	AddLesson(ctx context.Context, arg AddLessonParams) error
	AddLibraryItem(ctx context.Context, arg AddLibraryItemParams) error
	AddQuiz(ctx context.Context, arg AddQuizParams) error
	AddQuizQuestion(ctx context.Context, arg AddQuizQuestionParams) error
	AddSyncLog(ctx context.Context, arg AddSyncLogParams) error
	AddUser(ctx context.Context, arg AddUserParams) error
	ClearSyncLog(ctx context.Context) error
	CountSyncLog(ctx context.Context) (int64, error)
	DeleteCompletedLessons(ctx context.Context, userID string) error
	GetCompletedLessonIDs(ctx context.Context, userID string) ([]string, error)
	GetCourse(ctx context.Context, id string) (Course, error)
	GetCourses(ctx context.Context) ([]Course, error)
	GetLesson(ctx context.Context, id string) (GetLessonRow, error)
	GetLessonsForCourse(ctx context.Context, courseID string) ([]GetLessonsForCourseRow, error)
	GetLibraryItem(ctx context.Context, id string) (LibraryItem, error)
	GetLibraryItems(ctx context.Context) ([]LibraryItem, error)
	GetQuiz(ctx context.Context, id string) (Quiz, error)
	GetQuizQuestions(ctx context.Context, quizID string) ([]QuizQuestion, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserByRole(ctx context.Context, role string) (User, error)
	ListSyncLog(ctx context.Context) ([]string, error)
	TotalDiskKB(ctx context.Context) (interface{}, error)
	UpdateLesson(ctx context.Context, arg UpdateLessonParams) error
	UpdateLibraryItem(ctx context.Context, arg UpdateLibraryItemParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
