// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quiz_grades.sql

package dbgen

import (
	"context"
)

const getUserCoursePoints = `-- name: GetUserCoursePoints :one
SELECT COALESCE(SUM(quiz_grades.grade), 0)
FROM quiz_grades
JOIN quizzes ON quizzes.id = quiz_grades.quiz_id
WHERE quiz_grades.user_id = ? AND quizzes.course_id = ?
`

type GetUserCoursePointsParams struct {
	UserID   string
	CourseID string
}

func (q *Queries) GetUserCoursePoints(ctx context.Context, arg GetUserCoursePointsParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getUserCoursePoints, arg.UserID, arg.CourseID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const upsertQuizGrade = `-- name: UpsertQuizGrade :exec
INSERT INTO quiz_grades (user_id, quiz_id, grade, graded_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (user_id, quiz_id) DO UPDATE SET grade = excluded.grade, graded_at = excluded.graded_at
`

type UpsertQuizGradeParams struct {
	UserID   string
	QuizID   string
	Grade    int64
	GradedAt string
}

func (q *Queries) UpsertQuizGrade(ctx context.Context, arg UpsertQuizGradeParams) error {
	_, err := q.db.ExecContext(ctx, upsertQuizGrade,
		arg.UserID,
		arg.QuizID,
		arg.Grade,
		arg.GradedAt,
	)
	return err
}
