// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quiz_links.sql

package dbgen

import (
	"context"
	"database/sql"
)

const addQuizLink = `-- name: AddQuizLink :exec
INSERT INTO quiz_links (source_quiz_id, target_id, target_type) VALUES (?, ?, ?)
`

type AddQuizLinkParams struct {
	SourceQuizID string
	TargetID     string
	TargetType   string
}

func (q *Queries) AddQuizLink(ctx context.Context, arg AddQuizLinkParams) error {
	_, err := q.db.ExecContext(ctx, addQuizLink, arg.SourceQuizID, arg.TargetID, arg.TargetType)
	return err
}

const deleteQuizLinks = `-- name: DeleteQuizLinks :exec
DELETE FROM quiz_links WHERE source_quiz_id = ?
`

func (q *Queries) DeleteQuizLinks(ctx context.Context, sourceQuizID string) error {
	_, err := q.db.ExecContext(ctx, deleteQuizLinks, sourceQuizID)
	return err
}

const getQuizLinkedLessons = `-- name: GetQuizLinkedLessons :many
SELECT lessons.id, lessons.course_id, lessons.title, courses.title AS course_title
FROM quiz_links
JOIN lessons ON lessons.id = quiz_links.target_id
JOIN courses ON courses.id = lessons.course_id
WHERE quiz_links.source_quiz_id = ? AND quiz_links.target_type = 'lesson'
ORDER BY lessons.rowid
`

type GetQuizLinkedLessonsRow struct {
	ID          string
	CourseID    string
	Title       string
	CourseTitle string
}

func (q *Queries) GetQuizLinkedLessons(ctx context.Context, sourceQuizID string) ([]GetQuizLinkedLessonsRow, error) {
	rows, err := q.db.QueryContext(ctx, getQuizLinkedLessons, sourceQuizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuizLinkedLessonsRow
	for rows.Next() {
		var i GetQuizLinkedLessonsRow
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.CourseTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuizLinkedLibraryItems = `-- name: GetQuizLinkedLibraryItems :many
SELECT library_items.id, library_items.title, library_items.type, library_items.category, library_items.size_kb, library_items.mime_type, library_items.original_filename, library_items.uploaded_at, library_items.modified_at, library_items.duration, library_items.resolution, library_items.file_path, library_items.uploaded_by, users.name AS uploaded_by_name
FROM quiz_links
JOIN library_items ON library_items.id = quiz_links.target_id
LEFT JOIN users ON library_items.uploaded_by = users.id
WHERE quiz_links.source_quiz_id = ? AND quiz_links.target_type = 'library_item'
ORDER BY library_items.rowid
`

type GetQuizLinkedLibraryItemsRow struct {
	ID               string
	Title            string
	Type             string
	Category         string
	SizeKb           int64
	MimeType         string
	OriginalFilename string
	UploadedAt       string
	ModifiedAt       string
	Duration         sql.NullString
	Resolution       sql.NullString
	FilePath         string
	UploadedBy       sql.NullString
	UploadedByName   sql.NullString
}

func (q *Queries) GetQuizLinkedLibraryItems(ctx context.Context, sourceQuizID string) ([]GetQuizLinkedLibraryItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getQuizLinkedLibraryItems, sourceQuizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuizLinkedLibraryItemsRow
	for rows.Next() {
		var i GetQuizLinkedLibraryItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Type,
			&i.Category,
			&i.SizeKb,
			&i.MimeType,
			&i.OriginalFilename,
			&i.UploadedAt,
			&i.ModifiedAt,
			&i.Duration,
			&i.Resolution,
			&i.FilePath,
			&i.UploadedBy,
			&i.UploadedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
