// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quizzes.sql

package dbgen

import (
	"context"
	"database/sql"
)

const addQuiz = `-- name: AddQuiz :exec
INSERT INTO quizzes (id, course_id, lesson_id, title, description, value) VALUES (?, ?, ?, ?, ?, ?)
`

type AddQuizParams struct {
	ID          string
	CourseID    string
	LessonID    sql.NullString
	Title       string
	Description string
	Value       int64
}

func (q *Queries) AddQuiz(ctx context.Context, arg AddQuizParams) error {
	_, err := q.db.ExecContext(ctx, addQuiz,
		arg.ID,
		arg.CourseID,
		arg.LessonID,
		arg.Title,
		arg.Description,
		arg.Value,
	)
	return err
}

const addQuizQuestion = `-- name: AddQuizQuestion :exec
INSERT INTO quiz_questions (id, quiz_id, ordinal, text, options_json, correct_index)
VALUES (?, ?, ?, ?, ?, ?)
`

type AddQuizQuestionParams struct {
	ID           string
	QuizID       string
	Ordinal      int64
	Text         string
	OptionsJson  string
	CorrectIndex int64
}

func (q *Queries) AddQuizQuestion(ctx context.Context, arg AddQuizQuestionParams) error {
	_, err := q.db.ExecContext(ctx, addQuizQuestion,
		arg.ID,
		arg.QuizID,
		arg.Ordinal,
		arg.Text,
		arg.OptionsJson,
		arg.CorrectIndex,
	)
	return err
}

const deleteQuizQuestions = `-- name: DeleteQuizQuestions :exec
DELETE FROM quiz_questions WHERE quiz_id = ?
`

func (q *Queries) DeleteQuizQuestions(ctx context.Context, quizID string) error {
	_, err := q.db.ExecContext(ctx, deleteQuizQuestions, quizID)
	return err
}

const getQuiz = `-- name: GetQuiz :one
SELECT id, course_id, lesson_id, title, description, value FROM quizzes WHERE id = ?
`

func (q *Queries) GetQuiz(ctx context.Context, id string) (Quiz, error) {
	row := q.db.QueryRowContext(ctx, getQuiz, id)
	var i Quiz
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.LessonID,
		&i.Title,
		&i.Description,
		&i.Value,
	)
	return i, err
}

const getQuizQuestions = `-- name: GetQuizQuestions :many
SELECT id, quiz_id, ordinal, text, options_json, correct_index FROM quiz_questions WHERE quiz_id = ? ORDER BY ordinal
`

func (q *Queries) GetQuizQuestions(ctx context.Context, quizID string) ([]QuizQuestion, error) {
	rows, err := q.db.QueryContext(ctx, getQuizQuestions, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuizQuestion
	for rows.Next() {
		var i QuizQuestion
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.Ordinal,
			&i.Text,
			&i.OptionsJson,
			&i.CorrectIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuizzesForCourse = `-- name: GetQuizzesForCourse :many
SELECT id, course_id, lesson_id, title, description, value FROM quizzes WHERE course_id = ? ORDER BY rowid
`

func (q *Queries) GetQuizzesForCourse(ctx context.Context, courseID string) ([]Quiz, error) {
	rows, err := q.db.QueryContext(ctx, getQuizzesForCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Quiz
	for rows.Next() {
		var i Quiz
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.LessonID,
			&i.Title,
			&i.Description,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuiz = `-- name: UpdateQuiz :exec
UPDATE quizzes SET title = ?, description = ?, value = ? WHERE id = ?
`

type UpdateQuizParams struct {
	Title       string
	Description string
	Value       int64
	ID          string
}

func (q *Queries) UpdateQuiz(ctx context.Context, arg UpdateQuizParams) error {
	_, err := q.db.ExecContext(ctx, updateQuiz,
		arg.Title,
		arg.Description,
		arg.Value,
		arg.ID,
	)
	return err
}
