// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quizzes.sql

package dbgen

import (
	"context"
)

const addQuiz = `-- name: AddQuiz :exec
INSERT INTO quizzes (id, lesson_id) VALUES (?, ?)
`

type AddQuizParams struct {
	ID       string
	LessonID string
}

func (q *Queries) AddQuiz(ctx context.Context, arg AddQuizParams) error {
	_, err := q.db.ExecContext(ctx, addQuiz, arg.ID, arg.LessonID)
	return err
}

const addQuizQuestion = `-- name: AddQuizQuestion :exec
INSERT INTO quiz_questions (id, quiz_id, ordinal, text, options_json, correct_index)
VALUES (?, ?, ?, ?, ?, ?)
`

type AddQuizQuestionParams struct {
	ID           string
	QuizID       string
	Ordinal      int64
	Text         string
	OptionsJson  string
	CorrectIndex int64
}

func (q *Queries) AddQuizQuestion(ctx context.Context, arg AddQuizQuestionParams) error {
	_, err := q.db.ExecContext(ctx, addQuizQuestion,
		arg.ID,
		arg.QuizID,
		arg.Ordinal,
		arg.Text,
		arg.OptionsJson,
		arg.CorrectIndex,
	)
	return err
}

const getQuiz = `-- name: GetQuiz :one
SELECT id, lesson_id FROM quizzes WHERE id = ?
`

func (q *Queries) GetQuiz(ctx context.Context, id string) (Quiz, error) {
	row := q.db.QueryRowContext(ctx, getQuiz, id)
	var i Quiz
	err := row.Scan(&i.ID, &i.LessonID)
	return i, err
}

const getQuizQuestions = `-- name: GetQuizQuestions :many
SELECT id, quiz_id, ordinal, text, options_json, correct_index FROM quiz_questions WHERE quiz_id = ? ORDER BY ordinal
`

func (q *Queries) GetQuizQuestions(ctx context.Context, quizID string) ([]QuizQuestion, error) {
	rows, err := q.db.QueryContext(ctx, getQuizQuestions, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuizQuestion
	for rows.Next() {
		var i QuizQuestion
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.Ordinal,
			&i.Text,
			&i.OptionsJson,
			&i.CorrectIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
