// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: server_logs.sql

package dbgen

import (
	"context"
	"database/sql"
)

const addServerLog = `-- name: AddServerLog :exec
INSERT INTO server_logs (timestamp, level, message, fields)
VALUES (?, ?, ?, ?)
`

type AddServerLogParams struct {
	Timestamp string
	Level     string
	Message   string
	Fields    string
}

func (q *Queries) AddServerLog(ctx context.Context, arg AddServerLogParams) error {
	_, err := q.db.ExecContext(ctx, addServerLog,
		arg.Timestamp,
		arg.Level,
		arg.Message,
		arg.Fields,
	)
	return err
}

const countServerLogsByLevel = `-- name: CountServerLogsByLevel :many
SELECT level, COUNT(*) AS count FROM server_logs
WHERE timestamp >= ? AND timestamp <= ?
GROUP BY level
ORDER BY level
`

type CountServerLogsByLevelParams struct {
	Timestamp   string
	Timestamp_2 string
}

type CountServerLogsByLevelRow struct {
	Level string
	Count int64
}

func (q *Queries) CountServerLogsByLevel(ctx context.Context, arg CountServerLogsByLevelParams) ([]CountServerLogsByLevelRow, error) {
	rows, err := q.db.QueryContext(ctx, countServerLogsByLevel, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountServerLogsByLevelRow
	for rows.Next() {
		var i CountServerLogsByLevelRow
		if err := rows.Scan(&i.Level, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countServerLogsTotal = `-- name: CountServerLogsTotal :one
SELECT COUNT(*) FROM server_logs
WHERE timestamp >= ? AND timestamp <= ?
`

type CountServerLogsTotalParams struct {
	Timestamp   string
	Timestamp_2 string
}

func (q *Queries) CountServerLogsTotal(ctx context.Context, arg CountServerLogsTotalParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countServerLogsTotal, arg.Timestamp, arg.Timestamp_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldServerLogs = `-- name: DeleteOldServerLogs :execrows
DELETE FROM server_logs WHERE timestamp < ?
`

func (q *Queries) DeleteOldServerLogs(ctx context.Context, timestamp string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOldServerLogs, timestamp)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listServerLogs = `-- name: ListServerLogs :many
SELECT id, timestamp, level, message, fields FROM server_logs
WHERE level = COALESCE(?1, level)
  AND timestamp >= COALESCE(?2, timestamp)
  AND timestamp <= COALESCE(?3, timestamp)
ORDER BY id DESC
LIMIT ?5 OFFSET ?4
`

type ListServerLogsParams struct {
	Level  sql.NullString
	FromTs sql.NullString
	ToTs   sql.NullString
	Offset int64
	Limit  int64
}

func (q *Queries) ListServerLogs(ctx context.Context, arg ListServerLogsParams) ([]ServerLog, error) {
	rows, err := q.db.QueryContext(ctx, listServerLogs,
		arg.Level,
		arg.FromTs,
		arg.ToTs,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServerLog
	for rows.Next() {
		var i ServerLog
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Level,
			&i.Message,
			&i.Fields,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchServerLogs = `-- name: SearchServerLogs :many
SELECT server_logs.id, server_logs.timestamp, server_logs.level, server_logs.message, server_logs.fields FROM server_logs
JOIN server_logs_fts ON server_logs_fts.rowid = server_logs.id
WHERE server_logs_fts.message MATCH ?1
  AND level = COALESCE(?2, level)
  AND timestamp >= COALESCE(?3, timestamp)
  AND timestamp <= COALESCE(?4, timestamp)
ORDER BY server_logs.id DESC
LIMIT ?6 OFFSET ?5
`

type SearchServerLogsParams struct {
	Query  string
	Level  sql.NullString
	FromTs sql.NullString
	ToTs   sql.NullString
	Offset int64
	Limit  int64
}

func (q *Queries) SearchServerLogs(ctx context.Context, arg SearchServerLogsParams) ([]ServerLog, error) {
	rows, err := q.db.QueryContext(ctx, searchServerLogs,
		arg.Query,
		arg.Level,
		arg.FromTs,
		arg.ToTs,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServerLog
	for rows.Next() {
		var i ServerLog
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Level,
			&i.Message,
			&i.Fields,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
