// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync_log.sql

package dbgen

import (
	"context"
)

const addSyncLog = `-- name: AddSyncLog :exec
INSERT INTO sync_log (action, created_at) VALUES (?, ?)
`

type AddSyncLogParams struct {
	Action    string
	CreatedAt string
}

func (q *Queries) AddSyncLog(ctx context.Context, arg AddSyncLogParams) error {
	_, err := q.db.ExecContext(ctx, addSyncLog, arg.Action, arg.CreatedAt)
	return err
}

const clearSyncLog = `-- name: ClearSyncLog :exec
DELETE FROM sync_log
`

func (q *Queries) ClearSyncLog(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearSyncLog)
	return err
}

const countSyncLog = `-- name: CountSyncLog :one
SELECT COUNT(*) FROM sync_log
`

func (q *Queries) CountSyncLog(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSyncLog)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listSyncLog = `-- name: ListSyncLog :many
SELECT action FROM sync_log ORDER BY id
`

func (q *Queries) ListSyncLog(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSyncLog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var action string
		if err := rows.Scan(&action); err != nil {
			return nil, err
		}
		items = append(items, action)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
