// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync_ops.sql

package dbgen

import (
	"context"
)

const addSyncOp = `-- name: AddSyncOp :exec
INSERT OR IGNORE INTO sync_ops (origin_node, table_name, pk_json, op, hlc, payload, label, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type AddSyncOpParams struct {
	OriginNode string
	TableName  string
	PkJson     string
	Op         string
	Hlc        int64
	Payload    string
	Label      string
	CreatedAt  string
}

// OR IGNORE is the idempotency: an op already known by identity
// (origin_node, table_name, pk_json, hlc) is a no-op, which is what stops an op
// from being applied twice or bouncing between two nodes forever.
func (q *Queries) AddSyncOp(ctx context.Context, arg AddSyncOpParams) error {
	_, err := q.db.ExecContext(ctx, addSyncOp,
		arg.OriginNode,
		arg.TableName,
		arg.PkJson,
		arg.Op,
		arg.Hlc,
		arg.Payload,
		arg.Label,
		arg.CreatedAt,
	)
	return err
}

const countDeletesNotOlderThan = `-- name: CountDeletesNotOlderThan :one
SELECT COUNT(*) FROM sync_ops
WHERE table_name = ? AND pk_json = ? AND op = 'delete' AND hlc >= ?
`

type CountDeletesNotOlderThanParams struct {
	TableName string
	PkJson    string
	Hlc       int64
}

// The log doubles as the tombstone table: an upsert arriving after a delete of
// the same row at an equal or newer version must not resurrect it.
func (q *Queries) CountDeletesNotOlderThan(ctx context.Context, arg CountDeletesNotOlderThanParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeletesNotOlderThan, arg.TableName, arg.PkJson, arg.Hlc)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnackedOps = `-- name: CountUnackedOps :one
SELECT COUNT(*) FROM sync_ops
WHERE seq > (SELECT COALESCE(MIN(acked_seq), 0) FROM sync_readers)
`

// Ops no peer has confirmed reading yet. With no known reader that's every op,
// which is the honest answer: nothing has been delivered anywhere.
func (q *Queries) CountUnackedOps(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnackedOps)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSyncPeer = `-- name: GetSyncPeer :one
SELECT peer, node_id, last_seq, last_sync_at, last_error FROM sync_peers WHERE peer = ?
`

func (q *Queries) GetSyncPeer(ctx context.Context, peer string) (SyncPeer, error) {
	row := q.db.QueryRowContext(ctx, getSyncPeer, peer)
	var i SyncPeer
	err := row.Scan(
		&i.Peer,
		&i.NodeID,
		&i.LastSeq,
		&i.LastSyncAt,
		&i.LastError,
	)
	return i, err
}

const hasSyncOp = `-- name: HasSyncOp :one
SELECT COUNT(*) FROM sync_ops
WHERE origin_node = ? AND table_name = ? AND pk_json = ? AND hlc = ?
`

type HasSyncOpParams struct {
	OriginNode string
	TableName  string
	PkJson     string
	Hlc        int64
}

func (q *Queries) HasSyncOp(ctx context.Context, arg HasSyncOpParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasSyncOp,
		arg.OriginNode,
		arg.TableName,
		arg.PkJson,
		arg.Hlc,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listSyncPeers = `-- name: ListSyncPeers :many
SELECT peer, node_id, last_seq, last_sync_at, last_error FROM sync_peers ORDER BY peer
`

func (q *Queries) ListSyncPeers(ctx context.Context) ([]SyncPeer, error) {
	rows, err := q.db.QueryContext(ctx, listSyncPeers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncPeer
	for rows.Next() {
		var i SyncPeer
		if err := rows.Scan(
			&i.Peer,
			&i.NodeID,
			&i.LastSeq,
			&i.LastSyncAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxOpSeq = `-- name: MaxOpSeq :one
SELECT COALESCE(MAX(seq), 0) FROM sync_ops
`

func (q *Queries) MaxOpSeq(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxOpSeq)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const opsSince = `-- name: OpsSince :many
SELECT seq, origin_node, table_name, pk_json, op, hlc, payload, label, created_at FROM sync_ops WHERE seq > ? ORDER BY seq LIMIT ?
`

type OpsSinceParams struct {
	Seq   int64
	Limit int64
}

func (q *Queries) OpsSince(ctx context.Context, arg OpsSinceParams) ([]SyncOp, error) {
	rows, err := q.db.QueryContext(ctx, opsSince, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncOp
	for rows.Next() {
		var i SyncOp
		if err := rows.Scan(
			&i.Seq,
			&i.OriginNode,
			&i.TableName,
			&i.PkJson,
			&i.Op,
			&i.Hlc,
			&i.Payload,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSyncPeer = `-- name: RecordSyncPeer :exec
INSERT INTO sync_peers (peer, node_id, last_seq, last_sync_at, last_error)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (peer) DO UPDATE SET
    node_id = excluded.node_id,
    last_seq = excluded.last_seq,
    last_sync_at = excluded.last_sync_at,
    last_error = excluded.last_error
`

type RecordSyncPeerParams struct {
	Peer       string
	NodeID     string
	LastSeq    int64
	LastSyncAt string
	LastError  string
}

func (q *Queries) RecordSyncPeer(ctx context.Context, arg RecordSyncPeerParams) error {
	_, err := q.db.ExecContext(ctx, recordSyncPeer,
		arg.Peer,
		arg.NodeID,
		arg.LastSeq,
		arg.LastSyncAt,
		arg.LastError,
	)
	return err
}

const recordSyncReader = `-- name: RecordSyncReader :exec
INSERT INTO sync_readers (node_id, acked_seq, last_seen)
VALUES (?, ?, ?)
ON CONFLICT (node_id) DO UPDATE SET
    -- A cursor only ever moves forward: a peer that restarts from an old
    -- position must not make this node think its ops are undelivered again.
    acked_seq = MAX(sync_readers.acked_seq, excluded.acked_seq),
    last_seen = excluded.last_seen
`

type RecordSyncReaderParams struct {
	NodeID   string
	AckedSeq int64
	LastSeen string
}

func (q *Queries) RecordSyncReader(ctx context.Context, arg RecordSyncReaderParams) error {
	_, err := q.db.ExecContext(ctx, recordSyncReader, arg.NodeID, arg.AckedSeq, arg.LastSeen)
	return err
}

const unackedOpLabels = `-- name: UnackedOpLabels :many
SELECT label FROM sync_ops
WHERE seq > (SELECT COALESCE(MIN(acked_seq), 0) FROM sync_readers)
ORDER BY seq DESC LIMIT ?
`

func (q *Queries) UnackedOpLabels(ctx context.Context, limit int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, unackedOpLabels, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
