// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbgen

import (
	"context"
)

const addCompletedLesson = `-- name: AddCompletedLesson :exec
INSERT INTO user_completed_lessons (user_id, lesson_id) VALUES (?, ?)
`

type AddCompletedLessonParams struct {
	UserID   string
	LessonID string
}

func (q *Queries) AddCompletedLesson(ctx context.Context, arg AddCompletedLessonParams) error {
	_, err := q.db.ExecContext(ctx, addCompletedLesson, arg.UserID, arg.LessonID)
	return err
}

const addUser = `-- name: AddUser :exec
INSERT INTO users (id, name, email, password_hash, role) VALUES (?, ?, ?, ?, ?)
`

type AddUserParams struct {
	ID           string
	Name         string
	Email        string
	PasswordHash string
	Role         string
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) error {
	_, err := q.db.ExecContext(ctx, addUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	return err
}

const deleteCompletedLessons = `-- name: DeleteCompletedLessons :exec
DELETE FROM user_completed_lessons WHERE user_id = ?
`

func (q *Queries) DeleteCompletedLessons(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteCompletedLessons, userID)
	return err
}

const getCompletedLessonIDs = `-- name: GetCompletedLessonIDs :many
SELECT lesson_id FROM user_completed_lessons WHERE user_id = ?
`

func (q *Queries) GetCompletedLessonIDs(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getCompletedLessonIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var lesson_id string
		if err := rows.Scan(&lesson_id); err != nil {
			return nil, err
		}
		items = append(items, lesson_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, password_hash, role FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, role FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const getUserByRole = `-- name: GetUserByRole :one
SELECT id, name, email, password_hash, role FROM users WHERE role = ? LIMIT 1
`

func (q *Queries) GetUserByRole(ctx context.Context, role string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByRole, role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET name = ?, role = ? WHERE id = ?
`

type UpdateUserParams struct {
	Name string
	Role string
	ID   string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.Name, arg.Role, arg.ID)
	return err
}
